# Generated by Django 3.1.1 on 2020-10-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201004_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='success_attempt',
            field=models.IntegerField(default=2, verbose_name=0),
            preserve_default=False,
        ),
    ]
